version: 2

builds:
  - binary: gurl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -mod=vendor

release:
  prerelease: auto
  replace_existing_artifacts: true

universal_binaries:
  - replace: true

checksum:
  name_template: "checksums.txt"

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: ["zip"]

brews:
  - name: gurl
    repository:
      owner: geekyharsh05
      name: homebrew-gurl
    commit_author:
      name: geekyharsh05
      email: msg.theharsh@gmail.com
    homepage: "https://github.com/geekyharsh05/gurl"
    description: "Modern HTTP client CLI with JSON support"
    license: "MIT"
    skip_upload: false

scoops:
  - repository:
      owner: geekyharsh05
      name: scoop-bucket
    homepage: https://github.com/geekyharsh05/gurl
    description: Modern HTTP client CLI with JSON support
    license: MIT

nfpms:
  - id: linux-packages
    package_name: gurl
    vendor: "geekyharsh05"
    homepage: "https://github.com/geekyharsh05/gurl"
    maintainer: "Harsh <msg.theharsh@gmail.com>"
    description: "Modern HTTP client CLI with JSON support"
    license: "MIT"
    formats:
      - deb
      - rpm
